// Scheduled function: posts queued Bluesky content from velocity_posts.
//
// Picks up posts generated by velocity-engine.mts (status = 'queued',
// platform = 'bluesky'), posts them via the AT Protocol XRPC API using an
// app password (no dev-portal review needed, unlike X), and marks them
// posted or failed.
//
// Captures the created record's at:// URI and a human-viewable bsky.app URL
// so engagement-scanner.mts can look it up later and decide whether it's
// worth a follow-up "boost" post.
//
// Runs a few hours after velocity-engine.mts so there's always fresh content
// queued before this looks for it. Offset from x-poster.mts (15:00) and
// reddit-poster.mts (16:30) so no two posters contend for the same cold
// start window.

import type { Config } from '@netlify/functions'
import { getDatabase } from '@netlify/database'

const BATCH_SIZE = Number(process.env.BLUESKY_POST_BATCH_SIZE || 1)
const SERVICE = process.env.BLUESKY_SERVICE || 'https://bsky.social'

interface QueuedPost {
  id: string
  content: string
}

interface Session {
  accessJwt: string
  did: string
}

// Bluesky app passwords (bsky.app/settings/app-passwords) authenticate via a
// plain createSession call — no OAuth flow, no app review, works immediately
// like the Reddit script-app grant does.
async function createSession(): Promise<Session> {
  const identifier = process.env.BLUESKY_IDENTIFIER
  const password = process.env.BLUESKY_APP_PASSWORD
  if (!identifier || !password) {
    throw new Error('missing BLUESKY_IDENTIFIER or BLUESKY_APP_PASSWORD env vars')
  }

  const res = await fetch(`${SERVICE}/xrpc/com.atproto.server.createSession`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ identifier, password }),
  })
  if (!res.ok) throw new Error(`createSession failed: ${res.status}`)
  const data = (await res.json()) as { accessJwt?: string; did?: string }
  if (!data.accessJwt || !data.did) throw new Error('no accessJwt/did in createSession response')
  return { accessJwt: data.accessJwt, did: data.did }
}

async function submitPost(session: Session, text: string): Promise<{ uri: string }> {
  const res = await fetch(`${SERVICE}/xrpc/com.atproto.repo.createRecord`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${session.accessJwt}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      repo: session.did,
      collection: 'app.bsky.feed.post',
      record: {
        text,
        createdAt: new Date().toISOString(),
        // $type is required on the record itself by the AT Protocol lexicon.
        $type: 'app.bsky.feed.post',
      },
    }),
  })
  if (!res.ok) {
    const body = await res.text().catch(() => '')
    throw new Error(`createRecord failed: ${res.status} ${body}`)
  }
  const data = (await res.json()) as { uri?: string }
  if (!data.uri) throw new Error('no uri in createRecord response')
  return { uri: data.uri }
}

// Build the human-viewable bsky.app URL from an at:// post URI. URI shape is
// at://<did>/app.bsky.feed.post/<rkey> — the web viewer wants the handle (or
// did) plus that trailing rkey.
function webUrlFromUri(uri: string, handleOrDid: string): string | null {
  const rkey = uri.split('/').pop()
  if (!rkey) return null
  return `https://bsky.app/profile/${handleOrDid}/post/${rkey}`
}

export default async (_req: Request) => {
  let session: Session
  try {
    session = await createSession()
  } catch (err) {
    console.error('[bluesky-poster] auth failed:', (err as Error).message)
    return Response.json({ posted: 0, skipped: (err as Error).message })
  }

  const db = getDatabase()
  const queued = (await db.sql`
    SELECT id, content FROM velocity_posts
    WHERE platform = 'bluesky' AND status = 'queued'
    ORDER BY created_at ASC
    LIMIT ${BATCH_SIZE}
  `) as QueuedPost[]

  if (!queued.length) {
    console.log('[bluesky-poster] nothing queued to post')
    return Response.json({ posted: 0 })
  }

  const identifier = process.env.BLUESKY_IDENTIFIER as string // present — createSession already validated it

  let posted = 0
  for (const post of queued) {
    // Bluesky caps a single post at 300 graphemes — trim defensively even
    // though velocity-engine.mts is prompted to stay under that.
    const text = post.content.length > 300 ? post.content.slice(0, 297) + '...' : post.content
    try {
      const { uri } = await submitPost(session, text)
      const url = webUrlFromUri(uri, identifier)
      await db.sql`
        UPDATE velocity_posts
        SET status = 'posted', posted_at = now(), platform_post_id = ${uri}, platform_post_url = ${url}
        WHERE id = ${post.id}
      `
      posted++
      console.log(`[bluesky-poster] posted ${post.id} -> ${url ?? '(no url captured)'}`)
    } catch (err) {
      console.error(`[bluesky-poster] failed to post ${post.id}:`, (err as Error).message)
      await db.sql`UPDATE velocity_posts SET status = 'failed' WHERE id = ${post.id}`
    }
  }

  return Response.json({ posted, attempted: queued.length })
}

export const config: Config = {
  // A few hours after velocity-engine.mts (12:00 UTC), offset from
  // x-poster.mts (15:00) and reddit-poster.mts (16:30).
  schedule: '30 17 * * *',
}
