// Scheduled function: MultiAds campaign sweep.
//
// Auto-generates marketing-agent campaigns on a schedule so they don't
// require a manual click in /admin. This is the Netlify-native replacement
// for container/ads/campaign-scheduler.mjs, which does the same sweep but
// only runs while the container (multicontainer) is up — if it isn't running
// continuously, that scheduler never fires. This function runs on Netlify's
// own infrastructure regardless of whether the container is running, so
// campaigns keep getting generated even if multicontainer is closed.
//
// Netlify does not allow scheduled functions to be invoked over HTTP, so
// (mirroring indexnow-submit.mts) there is nothing here to call directly —
// it just runs on its cron.
//
// Safe to run alongside the container's own scheduler if that's ever active
// too: staleness is checked against the campaigns table itself (MAX(created_at)
// per sku), so a sku generated by either scheduler is no longer "due" for the
// other. Set MULTIADS_ENABLED=false in container/.env if you want to disable
// the container-side one entirely and rely on this instead.
//
// Env vars (all optional, sensible defaults — same names/semantics as the
// container scheduler, minus MULTIADS_INTERVAL_HOURS since the schedule below
// replaces that):
//   MULTIADS_ENABLED     'false' to disable entirely (default: on)
//   MULTIADS_STALE_DAYS  regenerate a sku's campaign after this many days (default: 30)
//   MULTIADS_BATCH_SIZE  max campaigns generated per run, to bound API spend (default: 3)

import type { Config } from '@netlify/functions'
import { getDatabase } from '@netlify/database'
import { loadCatalog } from '../lib/db.mjs'
import { generateCampaign } from './marketing-agent.mts'
import { submitUrls } from '../lib/indexnow.mjs'

const ENABLED = process.env.MULTIADS_ENABLED !== 'false'
const STALE_DAYS = Number(process.env.MULTIADS_STALE_DAYS || 30)
const BATCH_SIZE = Number(process.env.MULTIADS_BATCH_SIZE || 3)

async function getLastCampaignDates(): Promise<Map<string, Date | null>> {
  const db = getDatabase()
  const rows = (await db.sql`
    SELECT sku, MAX(created_at) AS last_created
    FROM campaigns
    GROUP BY sku
  `) as any[]
  const map = new Map<string, Date | null>()
  for (const row of rows) {
    map.set(row.sku, row.last_created ? new Date(row.last_created) : null)
  }
  return map
}

function isStale(lastCreated: Date | null | undefined): boolean {
  if (!lastCreated) return true
  const ageDays = (Date.now() - lastCreated.getTime()) / 86_400_000
  return ageDays >= STALE_DAYS
}

export default async (req: Request) => {
  if (!ENABLED) {
    console.log('[multiads-scheduler] disabled (MULTIADS_ENABLED=false)')
    return Response.json({ generated: 0, attempted: 0, skipped: 'disabled' })
  }

  const { products } = await loadCatalog()
  const lastBySku = await getLastCampaignDates()

  // The whole-store campaign is its own row keyed 'STORE' in the campaigns table.
  const targets = [
    { sku: 'STORE', label: 'the whole store' },
    ...products.map((p) => ({ sku: p.sku, label: p.name })),
  ]

  const due = targets.filter((t) => isStale(lastBySku.get(t.sku))).slice(0, BATCH_SIZE)

  if (!due.length) {
    console.log('[multiads-scheduler] no campaigns due — everything within the staleness window')
    return Response.json({ generated: 0, attempted: 0 })
  }

  console.log(`[multiads-scheduler] generating ${due.length} campaign(s): ${due.map((d) => d.label).join(', ')}`)

  const origin = new URL(req.url).origin
  let generated = 0
  for (const t of due) {
    try {
      const result = await generateCampaign({ sku: t.sku === 'STORE' ? '' : t.sku, goal: '' })
      console.log(`[multiads-scheduler] campaign generated for ${t.label} (persisted: ${result.persisted})`)
      if (result.persisted) {
        generated++
        const campaignId = result.campaign?.id
        if (campaignId) {
          const updateUrl = `${origin}/updates/${campaignId}`
          try {
            const idxResult = await submitUrls([updateUrl])
            console.log(`[multiads-scheduler] IndexNow submitted ${updateUrl} — HTTP ${idxResult.status}`)
          } catch (err) {
            // Non-fatal: the twice-daily indexnow-submit.mts sweep will pick this
            // URL up from the sitemap regardless, just up to 12h later.
            console.error(`[multiads-scheduler] IndexNow submission failed for ${updateUrl}:`, (err as Error).message)
          }
        }
      }
    } catch (err) {
      console.error(`[multiads-scheduler] failed to generate campaign for ${t.label}:`, (err as Error).message)
    }
  }

  return Response.json({ generated, attempted: due.length })
}

export const config: Config = {
  // Once a day, off-peak — same cadence as the container scheduler's default
  // 24h interval check. The exact hour doesn't matter; staleness is measured
  // in days against created_at, not against a specific time of day.
  schedule: '0 13 * * *',
}
