// Scheduled function: posts queued Reddit content from velocity_posts.
//
// Picks up posts generated by velocity-engine.mts (status = 'queued',
// platform = 'reddit'), posts them via Reddit's OAuth API (script-app grant),
// and marks them posted or failed.
//
// velocity-engine.mts stores a Reddit variant as "title\n\nbody" in one
// content field — this splits that back into the title/text Reddit's submit
// endpoint expects.
//
// Captures the posted submission's fullname (t3_...) and permalink so
// engagement-scanner.mts can look it up later and decide whether it's worth
// a follow-up "boost" post.
//
// Runs a few hours after velocity-engine.mts so there's always fresh content
// queued before this looks for it. Offset from x-poster.mts's slot so the
// two never contend for the same cold-start window.

import type { Config } from '@netlify/functions'
import { getDatabase } from '@netlify/database'

const BATCH_SIZE = Number(process.env.REDDIT_POST_BATCH_SIZE || 1)
const SUBREDDIT = process.env.REDDIT_SUBREDDIT || 'indiebiz'
const USER_AGENT = process.env.REDDIT_USER_AGENT || 'jblessd-velocity-engine/1.0 by u/MultiNicheAI81'

interface QueuedPost {
  id: string
  content: string
}

interface SubmitResult {
  fullname: string | null // e.g. t3_abc123 — what /api/info expects
  url: string | null // human-viewable permalink
}

// Reddit "script" apps authenticate as the account itself via the password
// grant — no browser/redirect flow needed for a server-side poster like this.
async function getAccessToken(): Promise<string> {
  const clientId = process.env.REDDIT_CLIENT_ID
  const clientSecret = process.env.REDDIT_CLIENT_SECRET
  const username = process.env.REDDIT_USERNAME
  const password = process.env.REDDIT_PASSWORD
  if (!clientId || !clientSecret || !username || !password) {
    throw new Error('missing one or more REDDIT_* env vars')
  }

  const res = await fetch('https://www.reddit.com/api/v1/access_token', {
    method: 'POST',
    headers: {
      Authorization: 'Basic ' + Buffer.from(`${clientId}:${clientSecret}`).toString('base64'),
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': USER_AGENT,
    },
    body: new URLSearchParams({ grant_type: 'password', username, password }),
  })
  if (!res.ok) throw new Error(`token request failed: ${res.status}`)
  const data = (await res.json()) as { access_token?: string }
  if (!data.access_token) throw new Error('no access_token in response')
  return data.access_token
}

// The stored content is "title\n\nbody" (see velocity-engine.mts). Split on
// the first blank line rather than the last, so a body that itself contains
// blank lines (paragraph breaks) stays intact.
function splitTitleBody(content: string): { title: string; body: string } {
  const idx = content.indexOf('\n\n')
  if (idx === -1) return { title: content.slice(0, 300), body: '' }
  return { title: content.slice(0, idx).slice(0, 300), body: content.slice(idx + 2) }
}

async function submitPost(token: string, title: string, body: string): Promise<SubmitResult> {
  const res = await fetch('https://oauth.reddit.com/api/submit', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': USER_AGENT,
    },
    body: new URLSearchParams({
      sr: SUBREDDIT,
      kind: 'self',
      title,
      text: body,
      api_type: 'json',
    }),
  })
  if (!res.ok) throw new Error(`submit failed: ${res.status}`)
  const data = (await res.json()) as {
    json?: { errors?: unknown[]; data?: { id?: string; name?: string; url?: string } }
  }
  const errors = data.json?.errors
  if (errors && errors.length) throw new Error(`reddit rejected post: ${JSON.stringify(errors)}`)

  const submitData = data.json?.data
  return {
    fullname: submitData?.name ?? (submitData?.id ? `t3_${submitData.id}` : null),
    url: submitData?.url ?? null,
  }
}

export default async (_req: Request) => {
  let token: string
  try {
    token = await getAccessToken()
  } catch (err) {
    console.error('[reddit-poster] auth failed:', (err as Error).message)
    return Response.json({ posted: 0, skipped: (err as Error).message })
  }

  const db = getDatabase()
  const queued = (await db.sql`
    SELECT id, content FROM velocity_posts
    WHERE platform = 'reddit' AND status = 'queued'
    ORDER BY created_at ASC
    LIMIT ${BATCH_SIZE}
  `) as QueuedPost[]

  if (!queued.length) {
    console.log('[reddit-poster] nothing queued to post')
    return Response.json({ posted: 0 })
  }

  let posted = 0
  for (const post of queued) {
    const { title, body } = splitTitleBody(post.content)
    if (!title.trim()) {
      console.error(`[reddit-poster] ${post.id} has no usable title — marking failed`)
      await db.sql`UPDATE velocity_posts SET status = 'failed' WHERE id = ${post.id}`
      continue
    }
    try {
      const result = await submitPost(token, title, body)
      await db.sql`
        UPDATE velocity_posts
        SET status = 'posted', posted_at = now(), platform_post_id = ${result.fullname}, platform_post_url = ${result.url}
        WHERE id = ${post.id}
      `
      posted++
      console.log(`[reddit-poster] posted ${post.id} -> ${result.url ?? '(no url captured)'}`)
    } catch (err) {
      console.error(`[reddit-poster] failed to post ${post.id}:`, (err as Error).message)
      await db.sql`UPDATE velocity_posts SET status = 'failed' WHERE id = ${post.id}`
    }
  }

  return Response.json({ posted, attempted: queued.length })
}

export const config: Config = {
  // A few hours after velocity-engine.mts (12:00 UTC), offset from
  // x-poster.mts's 15:00 slot so the two scheduled posters don't contend for
  // the same cold-start window.
  schedule: '30 16 * * *',
}
