// Scheduled function: posts queued X (Twitter) content from velocity_posts.
//
// Picks up posts generated by velocity-engine.mts (status = 'queued',
// platform = 'x'), posts them via the X API using OAuth 1.0a user context
// (posts as @DupreJesse14633), and marks them posted or failed.
//
// Runs a few hours after velocity-engine.mts so there's always fresh content
// queued before this looks for it.

import type { Config } from '@netlify/functions'
import { getDatabase } from '@netlify/database'
import { TwitterApi } from 'twitter-api-v2'

const BATCH_SIZE = Number(process.env.X_POST_BATCH_SIZE || 1)

interface QueuedPost {
  id: string
  content: string
}

export default async (_req: Request) => {
  const apiKey = process.env.X_API_KEY
  const apiSecret = process.env.X_API_SECRET
  const accessToken = process.env.X_ACCESS_TOKEN
  const accessSecret = process.env.X_ACCESS_TOKEN_SECRET

  if (!apiKey || !apiSecret || !accessToken || !accessSecret) {
    console.error('[x-poster] missing one or more X_API_* env vars — skipping')
    return Response.json({ posted: 0, skipped: 'missing credentials' })
  }

  const db = getDatabase()
  const queued = (await db.sql`
    SELECT id, content FROM velocity_posts
    WHERE platform = 'x' AND status = 'queued'
    ORDER BY created_at ASC
    LIMIT ${BATCH_SIZE}
  `) as QueuedPost[]

  if (!queued.length) {
    console.log('[x-poster] nothing queued to post')
    return Response.json({ posted: 0 })
  }

  const client = new TwitterApi({
    appKey: apiKey,
    appSecret: apiSecret,
    accessToken,
    accessSecret,
  })
  const rw = client.readWrite

  let posted = 0
  for (const post of queued) {
    try {
      // X caps a single post at 280 chars — trim defensively even though
      // velocity-engine.mts is prompted to stay under that.
      const text = post.content.length > 280 ? post.content.slice(0, 277) + '...' : post.content
      await rw.v2.tweet(text)
      await db.sql`UPDATE velocity_posts SET status = 'posted', posted_at = now() WHERE id = ${post.id}`
      posted++
      console.log(`[x-poster] posted ${post.id}`)
    } catch (err) {
      console.error(`[x-poster] failed to post ${post.id}:`, (err as Error).message)
      await db.sql`UPDATE velocity_posts SET status = 'failed' WHERE id = ${post.id}`
    }
  }

  return Response.json({ posted, attempted: queued.length })
}

export const config: Config = {
  // A few hours after velocity-engine.mts (12:00 UTC) so content exists first.
  schedule: '0 15 * * *',
}
