-- Adds four new "developers" niche agent products covering the core
-- disciplines of running an LLM pipeline in production: cost-aware model
-- routing, inter-stage output validation, regression testing, and
-- long-document handling with source traceability. None of these overlap
-- the existing AI-AG-016 RAG Knowledge Base Agent (checked against the live
-- catalog before writing this).

INSERT INTO products (sku, name, category, niche, format, price, blurb, spec, llm_compatibility, meta_description) VALUES
('AI-AG-123', 'Model Cascade Router — Cheap-First, Escalate-on-Failure', 'agents', 'developers', 'System prompt + escalation config', 44, 'Sends every request to your cheapest capable model first, and only escalates to a stronger one when a real failure signal fires — a JSON-schema check fails, resampled outputs disagree on a self-consistency vote, or the model itself flags low confidence. Not a blind "always call the frontier model" fallback: most requests never escalate, and every one that does gets logged with the exact reason and the cost delta, so you can see what you''re paying more for and why.', '3-tier cascade (small → mid → frontier) + self-consistency check (n-sample majority vote) + JSON-schema gate + per-request escalation log with reason and cost delta', 'Claude, ChatGPT & Gemini', 'Routes every request to the cheapest capable model first, escalating only on a real failure signal — and logs why each escalation fired.'),
('AI-AG-124', 'Pipeline Schema Guard — Validate-and-Repair Between Steps', 'agents', 'developers', 'System prompt + validator config', 42, 'Sits between every step of a multi-stage LLM pipeline and refuses to pass a stage''s output forward until it validates against that stage''s JSON schema. A validation failure doesn''t get silently ignored or crash the run — it triggers a bounded repair loop that feeds the exact validator error back to the model, capped at a fixed number of retries, then fails loudly with the last error if it still can''t produce valid output. Built for the failure where one early malformed field quietly corrupts every step after it.', 'Per-stage JSON Schema definitions + repair-loop prompt template (capped retries, backoff) + explicit fail-loud path with last error surfaced, no silent pass-through', 'Claude, ChatGPT & Gemini', 'Validates every pipeline stage output against its schema before passing it on, auto-repairing on failure instead of corrupting later steps.'),
('AI-AG-125', 'Prompt Regression Eval Harness — Golden-Set Diffing', 'agents', 'developers', 'System prompt + eval rubric templates', 46, 'Catches the regression a prompt tweak introduces before a customer does. Runs your pipeline against a versioned golden set, diffs every new output against the last known-good run with both a rule-based scorer (fields, format, length bounds) and a model-graded rubric, and flags true regressions instead of normal model drift. The rubric grader can''t rubber-stamp a pass — it has to cite the specific line that changed and why it matters.', 'Golden-set versioning + dual scorer (rule-based + model-graded rubric) + diff report (regression vs. acceptable drift) + rubric grader required to cite the change, not just a pass/fail score', 'Claude, ChatGPT & Gemini', 'Diffs every new output against a versioned golden set with a rule-based and model-graded scorer, flagging real regressions before you ship.'),
('AI-AG-126', 'Long-Document Map-Reduce Pipeline — Traceable to Source', 'agents', 'developers', 'System prompt + chunking config', 39, 'Handles input that blows past your context window without silently truncating it or summarizing it into mush. Splits the document into token-budgeted chunks, maps a targeted extraction prompt over each one, then reduces the results — but every claim in the final output keeps a citation back to the exact chunk it came from, so you can check the summary against the source instead of trusting it blind.', 'Token-budget-aware chunking (configurable overlap) + map-extract prompt + reduce-merge prompt + per-claim chunk-citation format, no un-sourced synthesis', 'Claude, ChatGPT & Gemini', 'Chunks oversized documents by token budget, extracts and merges the results, and keeps every claim cited back to its source chunk.');
