-- Stores marketing campaigns generated by the AI Marketing Agent so they
-- survive reloads and can be reviewed and reused later. `sku` is 'STORE' for
-- whole-store campaigns, otherwise the product SKU the campaign promotes.
-- `assets` holds the generated channel content (taglines, social posts, email,
-- SEO copy, ad headlines) as JSON so the shape can evolve without a migration.
CREATE TABLE IF NOT EXISTS "campaigns" (
	"id" serial PRIMARY KEY,
	"sku" text NOT NULL,
	"product_name" text NOT NULL,
	"goal" text NOT NULL DEFAULT '',
	"source" text NOT NULL DEFAULT 'ai',
	"assets" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS campaigns_created_at_idx ON campaigns (created_at DESC);
