-- Stores complete, ready-to-paste Google Ads plans generated by the AI Google
-- Ads Builder agent so they survive reloads and can be reviewed, copied, and
-- regenerated later. `sku` is 'STORE' for whole-store plans, otherwise the
-- product SKU the plan promotes. `assets` holds the full ad package (responsive
-- search ad headlines and descriptions, keywords with match types, negative
-- keywords, sitelinks, callouts, structured snippets, display paths and the
-- final URL) as JSON so the shape can evolve without a migration.
CREATE TABLE IF NOT EXISTS "ad_drafts" (
	"id" serial PRIMARY KEY,
	"sku" text NOT NULL,
	"product_name" text NOT NULL,
	"goal" text NOT NULL DEFAULT '',
	"source" text NOT NULL DEFAULT 'ai',
	"assets" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ad_drafts_created_at_idx ON ad_drafts (created_at DESC);
