// Shared catalog types + a canonical fallback catalog.
//
// The database is the source of truth (see netlify/database/migrations). This
// constant is only used when the DB is unreachable or has not been seeded yet
// (e.g. a brand-new preview branch), so the storefront and the AI concierge
// still have something meaningful to work with instead of an empty page.

export interface Product {
  sku: string
  name: string
  category: 'prompts' | 'automations' | 'templates' | 'agents' | 'connectors' | 'host'
  niche: 'founders' | 'sales' | 'marketers' | 'developers' | 'writers' | 'students' | 'architects' | 'engineers' | 'office' | 'finance' | 'stores' | 'contractors'
  format: string
  price: number
  blurb: string
  spec: string
  /** Optional. A short, concrete estimate of setup/manual time this product
   *  saves (e.g. "~3.5 hrs per setup"). Shown as its own spec-sheet line
   *  when present; omitted entirely otherwise. */
  timeSaved?: string
}

export const CATEGORY_LABEL: Record<Product['category'], string> = {
  prompts: 'Prompt Packs',
  automations: 'Automation Blueprints',
  templates: 'Doc Templates',
  agents: 'Agent Configs',
  connectors: 'Connectors',
  host: 'Host Packs',
}

export const NICHE_LABEL: Record<Product['niche'], string> = {
  founders: 'Founders & Ops',
  sales: 'Sales & CS',
  marketers: 'Marketers',
  developers: 'Developers',
  writers: 'Writers',
  students: 'Students & Researchers',
  architects: 'Architects',
  engineers: 'Engineers',
  office: 'Office & Admin',
  finance: 'Finance & Investing',
  stores: 'Store & Site Owners',
  contractors: 'Contractors & Trades',
}

export const FALLBACK_CATALOG: Product[] = [
  { sku: 'AI-HOST-001', name: 'Meridian Host', category: 'host', niche: 'stores', format: '.zip · Pi / laptop host pack · one-time license', price: 99, blurb: 'For store owners leaving Netlify, Shopify, and rented hosts. Load your GitHub on a Pi or laptop, paste your Stripe key, take money on hardware you own. Not a copy of MultiNicheAI\'s catalog.', spec: 'One pack · your repo · your Stripe · Pi 4/5 64-bit or Kali/Debian/Ubuntu · firewall 22/80/443' },

  { sku: 'AI-HOST-002', name: 'Meridian Gate', category: 'host', niche: 'stores', format: '.zip · outbound AI proxy · one-time license', price: 59, blurb: 'Sits in front of every AI call on the same machine as Host. Customer data and Stripe keys do not leave unless you say so. Default is no. A receipt for what left.', spec: 'Same Pi / laptop as Host · outbound proxy · witness log · named human' },
  { sku: 'AI-AB-070', name: 'SWARM Intent Autopilot', category: 'automations', niche: 'stores', format: 'Installed app · GitHub source · one-time license', price: 79, blurb: 'Hijacks demand that already exists and evolves proof-first ads on autopilot. Maps a pain-utterance to a SKU, spawns eight organisms, kills losers. Not a Google Ads account.', spec: 'Chrome/Edge PWA · Android + Windows · local genome · copy-ready packets' },
  { sku: 'AI-AB-071', name: 'Local SEO Agency Blueprint', category: 'automations', niche: 'marketers', format: '5 Make.com blueprints + Notion report template \u00b7 one-time license', price: 75, blurb: 'Before you buy: try it on a real client site and watch it actually fetch and parse that page live \u2014 title, meta, schema, alt text, robots/sitemap \u2014 not a script reading out a canned script. Then the full system to run a local-SEO service on: that real audit, a Google Business Profile checklist, automated review-response drafts, a white-label monthly report, and the outreach script to land the first client. One license, unlimited clients \u2014 you are the agency.', spec: 'Live on-page scan (title/meta/schema/alt/robots, fetched for real) + GBP checklist + review-response automation + white-label report + outreach script \u00b7 unlimited clients', timeSaved: '~6 hrs saved per client per month' },
  { sku: 'AI-PP-116', name: 'Faceless Video Script-to-B-Roll Prompt Kit', category: 'prompts', niche: 'writers', format: '40 prompts \u00b7 PDF + Notion', price: 24, blurb: 'Script the hook, generate matched B-roll prompts for Runway or Midjourney, and get a shot list out the other end \u2014 built for faceless short-form channels so the visuals stop being an afterthought.', spec: 'Hook scripts + Runway/Midjourney B-roll prompts + shot-list export' },
  { sku: 'AI-AG-117', name: 'Brand Voice Memory Block', category: 'agents', niche: 'marketers', format: 'System prompt + Notion database template', price: 27, blurb: 'Stores each client\'s brand voice as a structured, reusable memory block instead of a paragraph pasted into every prompt \u2014 so an agency\'s output stops drifting toward generic AI text as accounts pile up.', spec: 'Brand-voice intake \u2192 structured memory block \u2192 consistent output across writers', timeSaved: '~1 hr saved per piece of client content' },
  { sku: 'AI-AG-118', name: 'Fieldhand', category: 'agents', niche: 'contractors', format: 'Web app \u00b7 offline HTML download \u00b7 one-time license', price: 29, blurb: 'Drafts contractor correspondence \u2014 claim responses, RFIs, RFPs, change orders, notices of delay, punch-list follow-ups \u2014 in plain contractor voice, then runs it through a built-in scrub pass that strips stock AI phrasing, em dashes, and hidden Unicode characters before it ever leaves the page. Upload any file type as source material; download the whole tool as one offline HTML file when you\'re done.', spec: '20 letter types across bids, RFIs, claims, and closeout \u00b7 any-format upload (text read in, photos sent as images) \u00b7 built-in AI-phrasing scrubber with a change report \u00b7 offline-capable download', timeSaved: '~30 min saved per letter drafted' },
  { sku: 'AI-AB-119', name: 'Supplier PO & Inventory Sync', category: 'automations', niche: 'stores', format: '.zip \u00b7 real Shopify + email (Resend), Slack summary optional \u00b7 one-time license', price: 39, blurb: 'Checks your real Shopify stock against reorder thresholds you set, and when one\u2019s crossed, builds and emails an actual purchase order \u2014 a real line-item CSV, a real email, to the real supplier \u2014 automatically. Not a blueprint you wire yourself in Make or Zapier: a working script from the first run. Multiple low SKUs for the same supplier get combined into one PO, not a flood of separate emails. Pairs with MultiConnect: Shopify if you own it, runs standalone if you don\u2019t.', spec: 'Shopify Admin API stock lookup + Resend email with CSV attachment + optional Slack run summary \u00b7 Node 18+, zero dependencies \u00b7 GitHub Actions workflow included, runs on a schedule', timeSaved: '~20 min saved per reorder cycle, per supplier' },
  { sku: 'AI-AG-120', name: 'File Organizer Agent', category: 'agents', niche: 'office', format: '.zip \u00b7 Node script, zero dependencies \u00b7 cron/launchd/Task Scheduler adapters included \u00b7 one-time license', price: 19, blurb: 'Points at any messy folder \u2014 Downloads, Desktop, a shared drive \u2014 and sorts it into categorized subfolders: Invoices & Receipts, Screenshots, Statements, Contracts, and more, by filename keyword plus extension. Every run is a dry-run plan by default; nothing moves on disk until you pass --apply. No account, no API key, and nothing phoning home unless you opt into the AI fallback for files the rules can\u2019t place. Runs once from the terminal or on a schedule via the included cron, launchd, and Windows Task Scheduler adapters.', spec: 'Rule-based classification (extension + filename keywords) \u00b7 optional --ai fallback via your own ANTHROPIC_API_KEY, filenames only, never contents \u00b7 Node 18+, zero dependencies, no build step \u00b7 cron.sh, launchd.plist, windows-task.ps1 adapters included', timeSaved: '~15 min saved per organizing pass' },
  { sku: 'AI-AB-121', name: 'Overdue Invoice Chaser', category: 'automations', niche: 'finance', format: '.zip \u00b7 real Stripe + email (Resend), Slack summary optional \u00b7 one-time license', price: 39, blurb: 'Pulls your real open invoices straight from Stripe, works out exactly how many days overdue each one is, and emails escalating reminders \u2014 friendly, firmer, final notice \u2014 at the thresholds you set, automatically. Not a blueprint you wire yourself in Make or Zapier: a working script from the first run. Tracks what it has already sent per invoice, so a customer three weeks late gets one reminder at the right level of urgency, never a flood of catch-up emails or a repeat of the same one.', spec: 'Stripe Invoices API lookup + configurable escalation ladder + Resend email (HTML + text) with a link to pay + optional Slack run digest (overdue count, reminders sent, total outstanding) \u00b7 Node 18+, zero dependencies \u00b7 GitHub Actions workflow included, runs on a schedule \u00b7 file-based dedupe state, no database', timeSaved: '~15 min saved per overdue invoice, per week' },
  { sku: 'AI-AB-122', name: 'Broken Link & Uptime Watchdog', category: 'automations', niche: 'developers', format: '.zip \u00b7 real sitemap crawl + email (Resend), Slack summary optional \u00b7 one-time license', price: 29, blurb: 'Reads your real sitemap.xml, checks every URL it lists against your real site \u2014 HEAD requests, falling back to GET, concurrency-limited so it stays a polite crawl \u2014 and optionally follows the outbound links found on those pages too. Emails you an actual digest of what\u2019s broken, with counts by error type and which page linked to it, automatically. Not a blueprint you wire yourself in Make or Zapier: a working script from the first run. No per-page pricing, no seat limit, no dashboard login \u2014 just a scheduled job on infrastructure you already have.', spec: 'Sitemap.xml (and sitemap-index) crawl + HEAD/GET link + uptime checks + optional outbound-link scan + Resend email digest (HTML + text) + optional Slack run summary \u00b7 Node 18+, zero dependencies \u00b7 GitHub Actions workflow included, runs on a schedule', timeSaved: '~30 min saved per manual link-audit pass' },
  { sku: 'AI-PP-001', name: 'Deep Work Prompt Pack', category: 'prompts', niche: 'founders', format: '120 prompts · PDF + Notion', price: 19, blurb: 'Prompts for prioritization, focus blocks, and end-of-day resets.', spec: 'Works with Claude, ChatGPT, Gemini' },
  { sku: 'AI-AB-002', name: 'Inbox Zero Automation', category: 'automations', niche: 'sales', format: 'Make.com blueprint', price: 29, blurb: 'Auto-sorts, drafts replies, and flags what needs a human.', spec: 'Gmail + Outlook compatible' },
  { sku: 'AI-AG-003', name: 'Meeting Notes Agent', category: 'agents', niche: 'founders', format: 'System prompt + template', price: 15, blurb: 'Turns raw transcripts into decisions, owners, and deadlines.', spec: 'Tuned for Claude Projects' },
  { sku: 'AI-TP-004', name: 'Weekly Planning Template', category: 'templates', niche: 'students', format: 'Notion template', price: 12, blurb: 'A weekly operating rhythm: plan Monday, review Friday.', spec: 'Duplicate-and-go setup' },
  { sku: 'AI-AB-005', name: 'Content Calendar Autopilot', category: 'automations', niche: 'marketers', format: 'Zapier blueprint', price: 24, blurb: 'Drafts posts from your notes and queues them by channel.', spec: 'Buffer + Notion + Sheets' },
  { sku: 'AI-PP-006', name: 'Research Assistant Prompts', category: 'prompts', niche: 'students', format: '45 prompts · PDF', price: 22, blurb: 'Structured prompts for literature scans and source comparison.', spec: 'Citation-aware formatting' },
  { sku: 'AI-TP-007', name: 'Client Onboarding Kit', category: 'templates', niche: 'sales', format: 'Notion + email templates', price: 34, blurb: 'Intake form, welcome sequence, and kickoff checklist in one kit.', spec: 'Editable branding block' },
  { sku: 'AI-AG-008', name: 'Daily Standup Bot', category: 'agents', niche: 'developers', format: 'Slack agent config', price: 18, blurb: 'Collects updates async and posts a clean summary every morning.', spec: 'Slack + Claude API' },
  { sku: 'AI-AG-067', name: 'MultiBøT', category: 'agents', niche: 'developers', format: '.zip · Python tool layer + desktop app + Agent Studio config', price: 49, blurb: 'A coding bot that plans vehicle routes, then proposes structurally different alternatives — with real libraries, not three near-identical heuristics. One model, one hat at a time: Architect, Builder, Builder, Critic. Comes as a real desktop app now too — pick a stop list, click Run, no command line required. The critic refuses to ship if the alternatives are just heuristic wobble.', spec: 'NetworkX + optional OR-Tools/OSMnx · one-click desktop app (build once, run anywhere) or CLI · baseline \u2192 named hypotheses \u2192 re-solve \u2192 defended alternative' },
  { sku: 'AI-TP-009', name: 'OKR Tracker Template', category: 'templates', niche: 'founders', format: 'Sheets template', price: 14, blurb: 'Set, track, and review OKRs without a separate tool.', spec: 'Google Sheets, no add-ons' },
  { sku: 'AI-AB-010', name: 'Personal CRM Automation', category: 'automations', niche: 'sales', format: 'Make.com blueprint', price: 25, blurb: 'Keeps contacts and follow-ups in sync automatically.', spec: 'Contacts + Calendar sync' },
  { sku: 'AI-PP-011', name: 'Writing Style Prompt Kit', category: 'prompts', niche: 'writers', format: '30 prompts · PDF', price: 16, blurb: 'Match tone and voice consistently across drafts.', spec: 'Includes 3 worked examples' },
  { sku: 'AI-AG-012', name: 'Financial Categorizer Agent', category: 'agents', niche: 'founders', format: 'Sheets + agent config', price: 27, blurb: 'Cleans up transaction data into a usable ledger.', spec: 'CSV in, clean ledger out' },
  { sku: 'AI-AB-013', name: 'Code Review Digest', category: 'automations', niche: 'developers', format: '.zip · real GitHub Actions workflow, Slack included · one-time license', price: 26, blurb: 'A real workflow that posts a prioritized PR digest to Slack on a schedule — not a blueprint you wire yourself. Flags what needs a human today, says so plainly when nothing does.', spec: 'GitHub Actions (scheduled) + GitHub API + Slack Block Kit · Node 18+, zero dependencies' },
  { sku: 'AI-PP-014', name: 'Landing Page Copy Prompts', category: 'prompts', niche: 'marketers', format: '35 prompts · PDF', price: 18, blurb: 'Copy prompts built for conversion testing.', spec: 'A/B-ready output format' },
  { sku: 'AI-PP-025', name: 'Viral Hook Prompt Pack', category: 'prompts', niche: 'marketers', format: '60 hook formulas · PDF + Notion', price: 23, blurb: 'Scroll-stopping opening lines, tuned to the rhythm of each platform.', spec: 'TikTok, Reels, X & LinkedIn presets' },
  { sku: 'AI-AG-026', name: 'Personal Research Analyst', category: 'agents', niche: 'students', format: 'Scheduled agent config', price: 29, blurb: 'A standing agent that tracks a topic and briefs you every week with sources, not guesses.', spec: 'Scheduled runs + citation checks' },
  { sku: 'AI-TP-027', name: 'Investor Update Template', category: 'templates', niche: 'founders', format: 'Notion + email template', price: 15, blurb: 'A monthly update that keeps investors warm, metrics honest, and your asks impossible to miss.', spec: 'Metrics block + clear ask section' },
  { sku: 'AI-AB-028', name: 'Release Notes Bot', category: 'automations', niche: 'developers', format: '.zip · real GitHub Actions workflow, commits your changelog · one-time license', price: 27, blurb: 'A real workflow that fires when you publish a GitHub Release: drafts customer-facing notes and an internal Slack summary from your actual merged PRs, commits CHANGELOG.md, sets the release body. Not a blueprint you wire yourself.', spec: 'GitHub Actions (release-triggered) + GitHub compare API + Slack · commits to your repo' },
  { sku: 'AI-PP-029', name: 'Voice & Tone Cloner', category: 'prompts', niche: 'writers', format: '25 prompts · interview-to-styleguide', price: 19, blurb: 'Capture any brand or personal voice into a reusable system prompt you can hand to any model.', spec: 'Outputs a drop-in style guide' },
  { sku: 'AI-AG-030', name: 'Customer Churn Sentinel', category: 'agents', niche: 'founders', format: 'Agent config + save-plays', price: 43, blurb: 'Watches usage and support signals and flags at-risk accounts while there is still time to save them.', spec: 'Signal scoring + outreach prompts' },
  { sku: 'AI-AG-115', name: 'MultiSignal', category: 'agents', niche: 'founders', format: 'System prompt + live signal fetch', price: 46, blurb: 'Give it a number that moved inside your business and it checks the outside world itself — live headlines and real Reddit discussion — for a plausible connection, timing checked, confidence stated, never dressed up as proof. When nothing outside actually connects, it says so instead of forcing a story.', spec: 'Fetches headlines + Reddit discussion automatically · timing-checked, not just correlated · NO LINK is a valid run · never claims proof, only plausibility' },
  { sku: 'AI-AG-112', name: 'MultiCascade', category: 'agents', niche: 'founders', format: 'System prompt + role cascade template', price: 42, blurb: 'Give it a goal and it runs your idea through a structured cascade — an architect scopes it, builders execute the pieces, and a critic has to name a real flaw before it ships, or say plainly why it found none. One model working through honest, visible passes — not a dashboard of fake teammates.', spec: 'Root defines scope, not headcount · every role\'s output shown, not merged · critic cannot rubber-stamp' },
  { sku: 'AI-AG-113', name: 'MultiAugment', category: 'agents', niche: 'office', format: 'System prompt + decision framework', price: 39, blurb: 'Flips the usual AI move on purpose — instead of a confident verdict, it shows the real tradeoffs, says plainly what it\'s unsure about, and ends every answer by naming whose call this actually is. Never executes anything on your behalf either — it prepares the move and hands it back for you to make.', spec: 'Real options over one verdict · flags its own uncertainty · never acts without a go-ahead · every answer ends with WHO DECIDES' },
  { sku: 'AI-TP-031', name: 'Architecture Decision Record Kit', category: 'templates', niche: 'architects', format: 'Notion + Markdown template', price: 19, blurb: 'Capture the decision, the options you rejected, and why — so the next architect inherits reasoning, not folklore.', spec: 'ADR + RFC + trade-off matrix' },
  { sku: 'AI-PP-032', name: 'System Design Prompt Pack', category: 'prompts', niche: 'architects', format: '50 prompts · PDF + Notion', price: 24, blurb: 'Pressure-test a design across scale, failure modes, and cost before you commit a single line.', spec: 'C4 diagrams + capacity math' },
  { sku: 'AI-AG-033', name: 'Threat Modeling Agent', category: 'agents', niche: 'architects', format: 'Agent config + STRIDE library', price: 41, blurb: 'Walks a proposed design and surfaces the attack paths, trust boundaries, and mitigations you missed.', spec: 'STRIDE + data-flow analysis' },
  { sku: 'AI-AB-034', name: 'Architecture Diagram Sync', category: 'automations', niche: 'architects', format: '.zip · real GitHub Actions workflow, commits the diagram · one-time license', price: 33, blurb: "A real workflow that regenerates a Mermaid diagram from your codebase's actual structure on every push to main — grounded in a real scan, nothing invented. Commits only when it genuinely changed. Not a blueprint you wire yourself.", spec: 'GitHub Actions (push-triggered) + regex-based import scan + Mermaid · zero dependencies' },
  { sku: 'AI-TP-035', name: 'Tech Radar Template', category: 'templates', niche: 'architects', format: 'Notion + Sheets template', price: 16, blurb: 'Track what your org should adopt, trial, or retire — with the rationale attached to each ring.', spec: 'Adopt / Trial / Assess / Hold' },
  { sku: 'AI-AG-036', name: 'RFC Review Agent', category: 'agents', niche: 'architects', format: 'Agent config + review rubric', price: 37, blurb: 'Reads a design doc like a principal engineer would and returns sharp, specific questions before the meeting.', spec: 'Scored against a design rubric' },
  { sku: 'AI-AB-037', name: 'Incident Postmortem Automation', category: 'automations', niche: 'engineers', format: '.zip · real PagerDuty webhook + Slack, CLI included · one-time license', price: 34, blurb: 'Turns an incident timeline into a blameless postmortem draft with owners assigned — automatically, on incident.resolved. Not a blueprint you wire yourself: a real webhook, a real Slack poster, and a CLI for one-off drafts, calling your own Claude API key.', spec: 'PagerDuty webhook (HMAC-verified) + Slack Block Kit + standalone CLI · Node 18+, zero dependencies' },
  { sku: 'AI-PP-038', name: 'Infrastructure-as-Code Prompt Pack', category: 'prompts', niche: 'engineers', format: '45 prompts · PDF', price: 22, blurb: 'Generate, review, and refactor Terraform and Kubernetes manifests without the copy-paste drift.', spec: 'Terraform + K8s + Helm' },
  { sku: 'AI-AG-039', name: 'On-Call Triage Agent', category: 'agents', niche: 'engineers', format: 'Agent config + runbook loader', price: 45, blurb: 'Reads the alert, pulls the runbook, and proposes the first three checks before you finish logging in.', spec: 'Alert-to-runbook mapping' },
  { sku: 'AI-AB-040', name: 'Data Pipeline Monitor', category: 'automations', niche: 'engineers', format: 'Airflow + Slack blueprint', price: 36, blurb: 'Catches silent pipeline failures and schema drift, then explains what broke in plain language.', spec: 'dbt + Airflow + Great Expectations' },
  { sku: 'AI-TP-041', name: 'Runbook Template Library', category: 'templates', niche: 'engineers', format: 'Notion + Markdown templates', price: 18, blurb: 'Operational runbooks your whole team can follow at 3am — deploys, rollbacks, and recovery.', spec: 'Deploy / rollback / restore plays' },
  { sku: 'AI-PP-042', name: 'Debugging Copilot Prompts', category: 'prompts', niche: 'engineers', format: '60 prompts · PDF + Notion', price: 20, blurb: 'Structured prompts that turn a stack trace and a hunch into a reproducible root cause.', spec: 'Repro → isolate → fix workflow' },
  { sku: 'AI-PP-043', name: 'Exam Study Prompt Pack', category: 'prompts', niche: 'students', format: '55 prompts · PDF + Notion', price: 14, blurb: 'Active-recall and spaced-repetition prompts that turn a dense syllabus into a study plan you can actually finish.', spec: 'Works with Claude, ChatGPT, Gemini' },
  { sku: 'AI-TP-044', name: 'Course Notes System', category: 'templates', niche: 'students', format: 'Notion template', price: 12, blurb: 'A Cornell-style notes workspace with summaries, cue columns, and one-click review pages for every class.', spec: 'Duplicate-and-go, one page per course' },
  { sku: 'AI-AG-045', name: 'Essay Feedback Agent', category: 'agents', niche: 'students', format: 'Agent config + rubric library', price: 24, blurb: 'Reads your draft like a TA would and returns line-level feedback on argument, structure, and clarity — never writes it for you.', spec: 'Rubric-scored, plagiarism-safe by design' },
  { sku: 'AI-PP-046', name: 'Lecture-to-Flashcards Prompts', category: 'prompts', niche: 'students', format: '30 prompts · Anki-ready', price: 13, blurb: 'Paste a lecture transcript or your notes and get clean question-and-answer cards ready to import.', spec: 'Anki + Quizlet CSV export' },
  { sku: 'AI-TP-047', name: 'Semester Planner Template', category: 'templates', niche: 'students', format: 'Notion + Sheets template', price: 15, blurb: 'Track every course, deadline, and grade in one place, with a running GPA that updates as you go.', spec: 'Assignment tracker + GPA calculator' },
  { sku: 'AI-AB-048', name: 'Citation Formatter Automation', category: 'automations', niche: 'students', format: 'Make.com blueprint', price: 19, blurb: 'Drop in a link or DOI and get a clean, correctly formatted reference added to your bibliography automatically.', spec: 'APA, MLA & Chicago · Zotero sync' },
  { sku: 'AI-AG-049', name: 'Study Buddy Tutor Agent', category: 'agents', niche: 'students', format: 'Agent config + subject presets', price: 22, blurb: 'A Socratic tutor that asks the next question instead of handing you the answer, so the concept actually sticks.', spec: 'Presets for STEM, humanities & languages' },
  { sku: 'AI-AG-111', name: 'Closed Chair', category: 'agents', niche: 'students', format: 'Agent config + packet schema + eval clips', price: 36, blurb: 'Office hours that only know your syllabus. Load the packet or the chair stays empty — it won\'t fetch the internet, invent a late policy, or finish the problem, and it sends you to the human professor when the packet is silent.', spec: 'Packet-only knowledge · refuses finished answers · syllabus-verb exam prep' },
  { sku: 'AI-PP-050', name: 'Professional Email Prompt Pack', category: 'prompts', niche: 'office', format: '60 prompts · PDF + Notion', price: 16, blurb: 'Say the hard thing well — declines, follow-ups, and status updates that stay warm and get read.', spec: 'Tone controls for every workplace situation' },
  { sku: 'AI-TP-051', name: 'Meeting Agenda & Minutes Template', category: 'templates', niche: 'office', format: 'Notion + Docs template', price: 12, blurb: 'Walk in with a tight agenda and walk out with decisions, owners, and dates already written down.', spec: 'Agenda + action-item tracker in one' },
  { sku: 'AI-AB-052', name: 'Expense Report Automation', category: 'automations', niche: 'office', format: 'Zapier blueprint', price: 23, blurb: 'Turns a folder of receipts into a categorized, submission-ready expense report without the manual typing.', spec: 'Gmail + Drive + Sheets · OCR line items' },
  { sku: 'AI-AG-053', name: 'Calendar Scheduling Agent', category: 'agents', niche: 'office', format: 'Agent config + calendar hooks', price: 26, blurb: 'Handles the back-and-forth of finding a time, then books the meeting and sends the invite for you.', spec: 'Google + Outlook calendar aware' },
  { sku: 'AI-TP-054', name: 'Standard Operating Procedure Kit', category: 'templates', niche: 'office', format: 'Notion + Markdown template', price: 17, blurb: 'Capture how work actually gets done so a task survives vacations, handoffs, and new hires.', spec: 'Step-by-step SOP + onboarding checklist' },
  // Finance & investing — a cutting-edge line, each runnable in-app after purchase
  { sku: 'AI-AG-055', name: 'Portfolio Rebalancing Analyst', category: 'agents', niche: 'finance', format: 'Agent config + drift rules', price: 44, blurb: 'Reads your holdings and target allocation, then tells you exactly what to buy and sell to get back on track.', spec: 'Drift bands + tax-lot aware' },
  { sku: 'AI-AG-056', name: 'Earnings Call Copilot', category: 'agents', niche: 'finance', format: 'Agent config + transcript loader', price: 46, blurb: 'Turns a raw earnings transcript into the thesis, the risks, and the three numbers that actually moved the stock.', spec: 'Guidance + sentiment + KPI extraction' },
  { sku: 'AI-AG-057', name: 'Personal CFO Agent', category: 'agents', niche: 'finance', format: 'Agent config + monthly review', price: 39, blurb: 'A standing agent that reviews your spending, spots the leaks, and gives you three moves to hit your savings goal.', spec: 'Cashflow + goal tracking' },
  { sku: 'AI-AG-058', name: 'DCF Valuation Agent', category: 'agents', niche: 'finance', format: 'Agent config + model presets', price: 49, blurb: 'Feed it the fundamentals and it builds a discounted-cash-flow valuation with a bull, base, and bear case.', spec: 'Sensitivity table + WACC presets' },
  { sku: 'AI-AG-094', name: '$Token Agent', category: 'agents', niche: 'finance', format: 'System prompt + weekly brief template', price: 44, blurb: 'Reads filings, headlines, and trend noise and returns a sourced shortlist — not a trade. You still click the button.', spec: 'Thesis + sources + kill-criteria · NO TRADE is a valid run' },
  { sku: 'AI-AG-114', name: '$Odds Agent', category: 'agents', niche: 'finance', format: 'System prompt + divergence watch template', price: 44, blurb: 'Paste a Polymarket link and it checks the live price and recent headlines itself, then flags a real divergence between the public case and the price — never a trade. Most people who think they have a real edge on these markets don\'t; this is built to help you find out, not promise you one.', spec: 'Fetches live price + headlines automatically · flags real divergence, not noise · NO FLAG is a valid run · never places a trade' },
  { sku: 'AI-AB-059', name: 'Receipt-to-Ledger Automation', category: 'automations', niche: 'finance', format: 'Zapier blueprint', price: 29, blurb: 'Turns a photo or PDF of a receipt into a categorized, tax-ready ledger entry — no manual typing.', spec: 'OCR + tax-category mapping' },
  { sku: 'AI-AB-060', name: 'Cashflow Forecast Automation', category: 'automations', niche: 'finance', format: 'Make.com blueprint', price: 33, blurb: 'Pulls your invoices and bills and projects a 13-week cashflow so you see the crunch before it hits.', spec: '13-week rolling forecast' },
  { sku: 'AI-PP-061', name: 'Financial Modeling Prompt Pack', category: 'prompts', niche: 'finance', format: '50 prompts · PDF + Sheets', price: 26, blurb: 'Build three-statement models, unit economics, and scenario analyses without staring at a blank spreadsheet.', spec: 'Excel + Google Sheets formulas' },
  { sku: 'AI-PP-062', name: 'Equity Research Prompt Pack', category: 'prompts', niche: 'finance', format: '45 prompts · PDF', price: 24, blurb: 'Structured prompts that turn a 10-K into an investment thesis with catalysts, risks, and a price target.', spec: '10-K / 10-Q teardown workflow' },
  { sku: 'AI-TP-063', name: 'Investor-Ready Financials Template', category: 'templates', niche: 'finance', format: 'Sheets + Notion template', price: 22, blurb: 'The revenue, burn, and runway model investors expect — filled in from your numbers, not a blank tab.', spec: 'P&L + burn + runway + cap table' },
  { sku: 'AI-TP-064', name: 'Personal Budget & Net-Worth Template', category: 'templates', niche: 'finance', format: 'Sheets template', price: 15, blurb: 'Track every account, bill, and goal in one place, with a net-worth line that updates as you go.', spec: '50/30/20 + net-worth tracker' },
  // Store & site owners — source-code products, delivered as real files under a
  // perpetual buy-once license. Priced above the rest of the catalog because the
  // buyer receives software they own, not a document. See
  // packages/site-audit-agent and netlify/lib/deliverables.mts (SKU_DELIVERABLES).
  { sku: 'AI-AG-065', name: 'Site Audit Agent (Source Code)', category: 'agents', niche: 'stores', format: '.zip download · one-command install · zero dependencies · perpetual license', price: 79, blurb: 'The maintenance agent that watches this store, rebuilt to run on any site. Unzip, run ./install.sh, and you have a site-audit command. Sixteen checks, four schedulers, no account and no subscription — you own the code.', spec: 'Runs on Node 18+ anywhere · CLI, cron, CI or serverless' },
  { sku: 'AI-CN-001', name: 'MultiConnect: Zapier/Webhook Bridge', category: 'connectors', niche: 'developers', format: 'Downloadable app · one-time license', price: 29, blurb: 'Connect your AI agent to thousands of apps — no code required. Send updates out and receive triggers in via Zapier or Make.', spec: 'Outbound + inbound webhooks · visual payload mapping · live test console' },
  { sku: 'AI-CN-002', name: 'MultiConnect: Shopify', category: 'connectors', niche: 'stores', format: 'Downloadable app · one-time license', price: 59, blurb: 'Give your AI agent real-time access to your Shopify store — inventory, orders, and instant triggers, all in sync.', spec: 'Product/inventory sync · order visibility · webhook triggers · read-only or read/write mode' },
  { sku: 'AI-CN-003', name: 'MultiConnect: Sheets/Airtable', category: 'connectors', niche: 'office', format: 'Downloadable app · one-time license', price: 35, blurb: 'Turn a spreadsheet into your agent\'s database. Two-way sync with Google Sheets or Airtable — no code needed.', spec: 'Row read/write · column mapping · two-way sync · Sheets + Airtable in one app' },
  { sku: 'AI-CN-004', name: 'MultiConnect: Email/CRM', category: 'connectors', niche: 'sales', format: 'Downloadable app · one-time license', price: 79, blurb: 'Let your agent handle email and contacts — safely. Draft, send, and follow up on leads with full approval control.', spec: 'Read/draft/send · CRM contact sync · inbound-triggered tasks · approval queue + send limits' },
  { sku: 'AI-CN-005', name: 'MultiConnect: Slack/Discord', category: 'connectors', niche: 'office', format: 'Downloadable app · one-time license', price: 25, blurb: 'Bring your AI agent into the channels you already use. Automated updates, alerts, and commands in Slack or Discord.', spec: 'Channel updates/alerts · slash-command support · per-event channel routing · Slack + Discord' },
  { sku: 'AI-CN-006', name: 'MultiWitness', category: 'connectors', niche: 'founders', format: 'Downloadable app · one-time license', price: 69, blurb: 'A tamper-evident, hash-chained log of what your AI agents actually did — proof you can hand to anyone, checkable without trusting a server.', spec: 'Zero deps · SHA-256 hash chain · offline CLI verify' },
  { sku: 'AI-CN-007', name: 'MultiGuard', category: 'connectors', niche: 'founders', format: 'Downloadable app · one-time license', price: 59, blurb: 'One dashboard for every MultiConnect tool you run, and one button to switch them all to read-only at once — instead of checking five separate dashboards during an incident.', spec: 'Zero deps · works with any connector, not just ours · offline-safe by design' },
  { sku: 'AI-CN-008', name: 'MultiVault', category: 'connectors', niche: 'founders', format: '.zip download · MCP server + CLI + search index · zero-dependency core · perpetual license · optional standalone binary', price: 79, blurb: 'A local, encrypted context snapshot of a folder and calendar file — with a BM25-ranked search index (the same ranking approach real search engines use) so large folders return only what\'s relevant instead of everything. Served automatically to Claude Desktop, Claude Code, and other MCP-aware AI tools, or pasted manually anywhere else. No account, no OAuth, no cloud storage, no embeddings, no AI model involved in ranking — it all runs locally, in this process. Optional tie-in with MultiWitness logs every context-serving event to a tamper-evident hash chain — provably local, provably logged.', spec: 'AES-256-GCM · BM25 ranking · incremental index · background watcher · MCP server (get_context, vault_status) · optional MultiWitness audit log' },
  { sku: 'AI-CN-009', name: 'MultiConnect: Google Docs', category: 'connectors', niche: 'founders', format: '.zip download · zero dependencies · perpetual license', price: 39, blurb: 'Exports Google Docs to local markdown files, one-way, on a schedule — so local-file tools (like MultiVault, sold separately) can see content that otherwise only exists in a Google Doc. Drive Desktop sync alone does not do this: a synced .gdoc is a pointer file back to Google\'s servers, not the document\'s actual content. This asks Google to convert each Doc to plain markdown server-side and writes the real result to a local folder you choose. Read-only Drive access, revocable anytime, zero npm dependencies.', spec: 'OAuth2 (installed-app flow) · Drive API v3 (read-only) · incremental export by modifiedTime · cron/launchd/Task Scheduler adapters included' },
]
