// Copyright (c) 2026 [SELLER]. All rights reserved.
// Licensed to a single purchaser under the terms in LICENSE.md.
// Redistribution or resale of this source, in whole or in part, is not permitted.

// Turning a report object into something a human reads.
//
// Three formats because the same audit is consumed three ways: a terminal (the
// CLI), a document the buyer forwards to a client or keeps as a record
// (markdown), and a machine (JSON, for a dashboard or an alerting webhook).
//
// Kept separate from the engine so the engine stays a pure function of the URL.

const SYMBOL = { passed: '✓', warning: '!', failed: '✗' }
const COLOR = { passed: '[32m', warning: '[33m', failed: '[31m' }
const RESET = '[0m'
const BOLD = '[1m'
const DIM = '[2m'

const ORDER = { failed: 0, warning: 1, passed: 2 }

/** Failures first — the report should open with what needs doing. */
function bySeverity(checks) {
  return [...checks].sort((a, b) => ORDER[a.status] - ORDER[b.status])
}

function scoreBand(score) {
  if (score >= 90) return 'passed'
  if (score >= 70) return 'warning'
  return 'failed'
}

function camelToWords(key) {
  return key.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/^./, (c) => c.toUpperCase())
}

/**
 * Terminal output. Colour is applied only when the caller says the stream is a
 * TTY, so piping to a file or a CI log produces clean text.
 *
 * @param {object} report
 * @param {object} [options]
 * @param {boolean} [options.color]
 */
export function toText(report, { color = false } = {}) {
  const paint = (status, text) => (color ? `${COLOR[status]}${text}${RESET}` : text)
  const bold = (text) => (color ? `${BOLD}${text}${RESET}` : text)
  const dim = (text) => (color ? `${DIM}${text}${RESET}` : text)

  const lines = ['']
  lines.push(bold(`Site audit — ${report.target}`))
  lines.push(
    `${paint(scoreBand(report.score), `Score ${report.score}/100`)}  ·  ${report.status}  ·  ${report.summary}`,
  )
  lines.push('')

  for (const check of bySeverity(report.checks)) {
    lines.push(`  ${paint(check.status, SYMBOL[check.status])} ${bold(check.name)}`)
    lines.push(`    ${dim(check.detail)}`)
  }

  const metrics = Object.entries(report.metrics ?? {}).filter(([, v]) => v !== null && v !== undefined)
  if (metrics.length) {
    lines.push('')
    lines.push(dim(`  ${metrics.map(([k, v]) => `${camelToWords(k)}: ${v}`).join('  ·  ')}`))
  }

  if (report.details?.broken?.length) {
    lines.push('')
    lines.push(`  ${bold('Broken links')}`)
    for (const broken of report.details.broken) {
      lines.push(dim(`    ${broken.url} → ${broken.status}`))
    }
  }

  lines.push('')
  lines.push(dim(`  Completed in ${report.durationMs}ms`))
  lines.push('')
  return lines.join('\n')
}

/**
 * A self-contained document the operator can keep, forward, or attach to an
 * invoice. No styling assumptions — it renders anywhere markdown does.
 */
export function toMarkdown(report) {
  const lines = [`# Site audit — ${report.target}`, '']
  lines.push(`**Score:** ${report.score}/100 · **Status:** ${report.status} · ${report.summary}`)
  lines.push('')

  const groups = [
    ['Fix these', report.checks.filter((c) => c.status === 'failed')],
    ['Worth improving', report.checks.filter((c) => c.status === 'warning')],
    ['Passing', report.checks.filter((c) => c.status === 'passed')],
  ]

  for (const [heading, checks] of groups) {
    if (!checks.length) continue
    lines.push(`## ${heading}`, '')
    for (const check of checks) lines.push(`- **${check.name}** — ${check.detail}`)
    lines.push('')
  }

  const metrics = Object.entries(report.metrics ?? {}).filter(([, v]) => v !== null && v !== undefined)
  if (metrics.length) {
    lines.push('## Measurements', '')
    for (const [key, value] of metrics) lines.push(`- ${camelToWords(key)}: ${value}`)
    lines.push('')
  }

  if (report.details?.broken?.length) {
    lines.push('## Broken links', '')
    for (const broken of report.details.broken) lines.push(`- ${broken.url} → ${broken.status}`)
    lines.push('')
  }

  lines.push('---', '')
  lines.push(
    `Generated by ${report.engine.name} v${report.engine.version} in ${report.durationMs}ms. ` +
      'Runs on your own infrastructure — no account, no third-party service.',
  )
  return lines.join('\n')
}

export function toJson(report) {
  return JSON.stringify(report, null, 2)
}
