-- Shareable "Live Proof" runs. When a shopper watches a product actually work
-- (the /api/demo stream), they can now save that run and share a public,
-- crawlable permalink at /proof/:id. Each row is one saved demonstration.
--
-- This turns the store's signature feature into a distribution loop: every
-- shared proof is an indexable landing page that shows a real tool doing real
-- work, with a CTA back into the store. Backs the /api/proof endpoint (write +
-- read) and the /proof/:id edge-rendered page.
--
-- `id` is a short, URL-safe public id generated by the function (not a serial),
-- so permalinks are unguessable-ish and don't leak volume. `scenario` is the
-- shopper's own situation when they tailored the run ('' for the default demo).
CREATE TABLE IF NOT EXISTS "proofs" (
	"id" text PRIMARY KEY,
	"sku" text NOT NULL,
	"product_name" text NOT NULL,
	"scenario" text NOT NULL DEFAULT '',
	"output" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS proofs_created_at_idx ON proofs (created_at DESC);
CREATE INDEX IF NOT EXISTS proofs_sku_idx ON proofs (sku);
